<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>aqua_wix.mwe</groupId>
  <artifactId>aqua_wix.mwe</artifactId>
  <version>0.0.1</version>

  <properties>
    <maven.compiler.release>25</maven.compiler.release>
  </properties>

  <build>
    <plugins>
<!--      <plugin>-->
<!--        <groupId>org.codehaus.mojo</groupId>-->
<!--        <artifactId>exec-maven-plugin</artifactId>-->
<!--        <version>3.6.3</version>-->
<!--        <executions>-->
<!--          <execution>-->
<!--            <phase>package</phase>-->
<!--            <goals>-->
<!--              <goal>exec</goal>-->
<!--            </goals>-->
<!--          </execution>-->
<!--        </executions>-->
<!--        <configuration>-->
<!--          <executable>jpackage</executable>-->
<!--          <arguments>-->
<!--            <argument>&#45;&#45;name</argument>-->
<!--            <argument>MyApp</argument>-->
<!--            <argument>&#45;&#45;dest</argument>-->
<!--            <argument>target</argument>-->
<!--            <argument>&#45;&#45;verbose</argument>-->
<!--            <argument>&#45;&#45;app-version</argument>-->
<!--            <argument>0.0.1</argument>-->
<!--            <argument>&#45;&#45;input</argument>-->
<!--            <argument>target</argument>-->
<!--            <argument>&#45;&#45;vendor</argument>-->
<!--            <argument>ACME</argument>-->
<!--            <argument>&#45;&#45;main-class</argument>-->
<!--            <argument>aqua_wix.mwe.MyApp</argument>-->
<!--            <argument>&#45;&#45;main-jar</argument>-->
<!--            <argument>aqua_wix.mwe-0.0.1.jar</argument>-->
<!--          </arguments>-->
<!--        </configuration>-->
<!--      </plugin>-->
    </plugins>
  </build>
</project>
